name: flutter_app_packager
description: Package your Flutter app into OS-specific bundles (.dmg, .exe, etc.) via Dart or the command line.
version: 0.3.2
homepage: https://github.com/leanflutter/flutter_distributor
publish_to: none # 待 msix 的 PR 合并后移除

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  app_package_maker: ^0.3.1
  archive: ^3.1.5
  io: ^1.0.3
  liquid_engine: ^0.2.2
  # msix: ^3.13.0
  msix:
    git:
      ref: feat/locate_msix_assets_path_from_script_file_directory
      url: https://github.com/lijy91/msix.git
  path: ^1.8.1
  shell_executor: ^0.1.2

dev_dependencies:
  dependency_validator: ^3.0.0
